### ISSUE TITLE
Erreur 401 depuis plusieurs semaines

### ISSUE THREAD

**Issue by JeedHome44** [jmvedrine/jeedom-surepetcare#1]
Tout passe en erreur 401 depuis un bon moment.

J'ai été sur l'app SureFlap et ca m'a demandé de changer mon password et d'accepter de nouvelles conditions.

Je pense donc qu'ils ont fait des modifications importantes.

Pouvez vous corriger le plugin pour que ça remarche correctement?

Merci

**Comment by jmvedrine** [comment]
Désolé mais chez moi tout marche normalement sur 2 Jeedoms différents 4.1 et 4.2.
Ça doit venir de votre système.

**Comment by jmvedrine** [comment]
Après réflexion je réalise que je fais tourner la version beta et que sur celle ci j'ai légèrement changé la procédure d'authentification. Donc au cas où vous utilisiez la version stable et où ce soit çà votre problème, j'ai publié une nouvelle version stable sur le market qui incorpore les changements de la version beta. Dites-moi si cela résout votre problème.

**Comment by JeedHome44** [comment]
Bonjour,

Je vais mettre à jour dans la journée et je vous tiens au courant.

Une erreur 401 généralement c'est un problème d'authentification ?

**Comment by JeedHome44** [comment]
Bon bah avec votre version stable ça marche niquel! C'était donc l'authentification de Sureflap qui avait changé.
Merci pour votre réactivité
